version: "3.10"
services:
  nginx-delay:
    image: nginx-delay:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-delay
    ports:
      - "80:80"
      - "443:443"
    cap_add:
      - NET_ADMIN
  nginx-nodelay:
    image: nginx-nodelay:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-nodelay
    ports:
      - "81:80"
      - "444:443"
    cap_add:
      - NET_ADMIN
